### ISSUE TITLE
create tech blog about Rafael's paper at ECIR

### ISSUE THREAD

**Issue by rjgsousa** [iFetch-chatbot/ifetch-chatbot.github.io#20]
**Acceptance Criteria**

- Create an article about Rafael paper
- Make sure we can track the performance of the page

**Supplementary Material**
- [ecir_2021_paper_architecture.pdf](https://github.com/iFetch-chatbot/ifetch-chatbot.github.io/files/6320618/ecir_2021_paper_architecture.pdf)
- [ecir_2021_blogpost.zip](https://github.com/iFetch-chatbot/ifetch-chatbot.github.io/files/6320623/ecir_2021_blogpost.zip)

**Comment by rafaelhferreira** [comment]
As discussed here are the additional images:
[example_conversational_search.pdf](https://github.com/iFetch-chatbot/ifetch-chatbot.github.io/files/6320829/example_conversational_search.pdf)
[summarization_example.pdf](https://github.com/iFetch-chatbot/ifetch-chatbot.github.io/files/6320830/summarization_example.pdf)

**Comment by rjgsousa** [comment]
![image](https://user-images.githubusercontent.com/124693/116258999-55f00800-a76d-11eb-82af-69a725f3e2ec.png)
![image](https://user-images.githubusercontent.com/124693/116259081-66a07e00-a76d-11eb-867e-3102dd60ff93.png)

pair-programming with @azevedo
both acceptance criteria are met.

/cc @iFetch-chatbot/farfetch-ifetch-team
