### ISSUE TITLE
Enumerate pages for ifetch website

### ISSUE THREAD

**Issue by pmoreirac** [iFetch-chatbot/ifetch-chatbot.github.io#48]

**Comment by rjgsousa** [comment]
All of the above seems pretty reasonable to me to be published as a tech blog on the ifetch website. Thanks for the background work conducted here, @pmoreirac

**Comment by pmoreirac** [comment]
Created issues #49, #50 and #51 to review the article contents before pushing to the website.

@iFetch-chatbot/farfetch-ifetch-team
